export const Messages = {
    FAILED: "Failed to process the request",
    SERVER_ERROR: "Internel server error",
    USER_EXIST: "User already exist",
    NO_ACCESS: "Unauthorized Access",
    NAME_REQUIRED: "Name is required",
    EMAIL_REQUIRED: "Email is required",
    PASSWORD_REQUIRED: "Password is required",
    TOKEN_REQUIRED: "Access denied. No token provided.",
    INVALID_ID: "invalid id, failed to lookup",
    INVALID_TOKEN: "Invalid authentication token.",
    INVALID_NAME: "Please enter a valid name (A - Z)",
    INVALID_EMAIL: "Please enter a valid email",
    LOGIN_SUCCESS: "Login successful",
    SIGNUP_SUCCESS: "Signup successful",
    USER_NOT_FOUND: "User not found",
    INVALID_CREDENTIALS: "Invalid email or password",
    NO_FILE: "No files selected to upload",
    ALL_FEILDs_REQUIRED: "All feilds are required",
    BLOG_CREATED: "Blog has been created",
    BLOG_NOT_FOUND: "Blog not found",
    BLOG_UPDATED: "Blog updated successfully",
    BLOG_DELETED: "Blog deleted successfully",
    NOT_AUTHORIZED: "You are not authorized to perform this action",
}